default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wubhub_development
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  <<: *default
  database: wubhub_test
  username: postgres
  password: password
  host: localhost
  port: 5432

production:
  <<: *default
  database: wubhub_production
  username: wubhub
  password: <%= ENV['WUBHUB_DATABASE_PASSWORD'] %>
