# Gemfile
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
ruby '3.1.2'

# Rails framework
gem 'rails', '~> 7.1.5'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 6.0'

# API & Auth
gem 'active_model_serializers', '~> 0.10.13'
gem 'bcrypt', '~> 3.1.7'
gem 'jwt', '~> 2.3'
gem 'rack-cors'

# File handling
gem 'aws-sdk-s3', '~> 1.114', require: false
gem 'image_processing', '~> 1.12'

# Performance
gem 'bootsnap', '>= 1.4.4', require: false

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'faker', '~> 3.2'
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails', '~> 6.2'
  gem 'shoulda-matchers', '~> 5.3'
  gem 'database_cleaner-active_record', '~> 2.1'

end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'secure_headers'
gem 'rack-attack'

